version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fp-ts-contrib
    versions:
    - 0.1.22
  - dependency-name: fp-ts
    versions:
    - 2.10.3
    - 2.9.4
  - dependency-name: jwks-rsa
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: "@pgtyped/cli"
    versions:
    - 0.10.2
  - dependency-name: monocle-ts
    versions:
    - 2.3.8
  - dependency-name: io-ts
    versions:
    - 2.2.15
  - dependency-name: typescript
    versions:
    - 4.1.4
